---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: cable-tester-config
  labels:
    app: cable-tester
data:
  config.json: |
    {
      "log_level": "info",
      "max_conns": 25000,
      "conn_speed": 1000,
      "log_format": "text",
      "endpoints": [
        "tcp://cable-cluster-0.cable:1883",
        "tcp://cable-cluster-1.cable:1883",
        "tcp://cable-cluster-2.cable:1883"
      ],
      "max_user_id": 100000,
      "max_channel_id": 100000,
      "message_interval": 20,
      "message_route": {
        "1": "user",
        "2": "channel"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cable-tester
  labels:
    app: cable-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cable-tester
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cable-tester
    spec:
      containers:
        - name: cable-tester
          imagePullPolicy: Always 
          image: sutext/cable-tester:latest
          volumeMounts:
            - name: config-volume
              mountPath: /config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: cable-tester-config
