---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cable-tester
  labels:
    app: cable-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cable-tester
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cable-tester
    spec:
      containers:
        - name: cable-tester
          imagePullPolicy: Always 
          image: sutext/cable-tester:latest
          env:
            - name: ENDPOINT
              value: "tcp://cable-cluster:1883"
            - name: FREQ
              value: "50"
