// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
)

type JoinRequest struct {
	Uid      string   `thrift:"uid,1" frugal:"1,default,string" json:"uid"`
	Channels []string `thrift:"channels,2" frugal:"2,default,list<string>" json:"channels"`
}

func NewJoinRequest() *JoinRequest {
	return &JoinRequest{}
}

func (p *JoinRequest) InitDefault() {
}

func (p *JoinRequest) GetUid() (v string) {
	return p.Uid
}

func (p *JoinRequest) GetChannels() (v []string) {
	return p.Channels
}
func (p *JoinRequest) SetUid(val string) {
	p.Uid = val
}
func (p *JoinRequest) SetChannels(val []string) {
	p.Channels = val
}

func (p *JoinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinRequest(%+v)", *p)
}

var fieldIDToName_JoinRequest = map[int16]string{
	1: "uid",
	2: "channels",
}

type JoinResponse struct {
	Count int32 `thrift:"count,1" frugal:"1,default,i32" json:"count"`
}

func NewJoinResponse() *JoinResponse {
	return &JoinResponse{}
}

func (p *JoinResponse) InitDefault() {
}

func (p *JoinResponse) GetCount() (v int32) {
	return p.Count
}
func (p *JoinResponse) SetCount(val int32) {
	p.Count = val
}

func (p *JoinResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinResponse(%+v)", *p)
}

var fieldIDToName_JoinResponse = map[int16]string{
	1: "count",
}

type PublishRequest struct {
	Channel string `thrift:"channel,1" frugal:"1,default,string" json:"channel"`
	Payload []byte `thrift:"payload,2" frugal:"2,default,binary" json:"payload"`
}

func NewPublishRequest() *PublishRequest {
	return &PublishRequest{}
}

func (p *PublishRequest) InitDefault() {
}

func (p *PublishRequest) GetChannel() (v string) {
	return p.Channel
}

func (p *PublishRequest) GetPayload() (v []byte) {
	return p.Payload
}
func (p *PublishRequest) SetChannel(val string) {
	p.Channel = val
}
func (p *PublishRequest) SetPayload(val []byte) {
	p.Payload = val
}

func (p *PublishRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishRequest(%+v)", *p)
}

var fieldIDToName_PublishRequest = map[int16]string{
	1: "channel",
	2: "payload",
}

type Service interface {
	Join(ctx context.Context, req *JoinRequest) (r *JoinResponse, err error)

	Leave(ctx context.Context, req *JoinRequest) (r *JoinResponse, err error)

	Publish(ctx context.Context, req *PublishRequest) (err error)
}

type ServiceJoinArgs struct {
	Req *JoinRequest `thrift:"req,1" frugal:"1,default,JoinRequest" json:"req"`
}

func NewServiceJoinArgs() *ServiceJoinArgs {
	return &ServiceJoinArgs{}
}

func (p *ServiceJoinArgs) InitDefault() {
}

var ServiceJoinArgs_Req_DEFAULT *JoinRequest

func (p *ServiceJoinArgs) GetReq() (v *JoinRequest) {
	if !p.IsSetReq() {
		return ServiceJoinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServiceJoinArgs) SetReq(val *JoinRequest) {
	p.Req = val
}

func (p *ServiceJoinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServiceJoinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceJoinArgs(%+v)", *p)
}

var fieldIDToName_ServiceJoinArgs = map[int16]string{
	1: "req",
}

type ServiceJoinResult struct {
	Success *JoinResponse `thrift:"success,0,optional" frugal:"0,optional,JoinResponse" json:"success,omitempty"`
}

func NewServiceJoinResult() *ServiceJoinResult {
	return &ServiceJoinResult{}
}

func (p *ServiceJoinResult) InitDefault() {
}

var ServiceJoinResult_Success_DEFAULT *JoinResponse

func (p *ServiceJoinResult) GetSuccess() (v *JoinResponse) {
	if !p.IsSetSuccess() {
		return ServiceJoinResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServiceJoinResult) SetSuccess(x interface{}) {
	p.Success = x.(*JoinResponse)
}

func (p *ServiceJoinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServiceJoinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceJoinResult(%+v)", *p)
}

var fieldIDToName_ServiceJoinResult = map[int16]string{
	0: "success",
}

type ServiceLeaveArgs struct {
	Req *JoinRequest `thrift:"req,1" frugal:"1,default,JoinRequest" json:"req"`
}

func NewServiceLeaveArgs() *ServiceLeaveArgs {
	return &ServiceLeaveArgs{}
}

func (p *ServiceLeaveArgs) InitDefault() {
}

var ServiceLeaveArgs_Req_DEFAULT *JoinRequest

func (p *ServiceLeaveArgs) GetReq() (v *JoinRequest) {
	if !p.IsSetReq() {
		return ServiceLeaveArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServiceLeaveArgs) SetReq(val *JoinRequest) {
	p.Req = val
}

func (p *ServiceLeaveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServiceLeaveArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceLeaveArgs(%+v)", *p)
}

var fieldIDToName_ServiceLeaveArgs = map[int16]string{
	1: "req",
}

type ServiceLeaveResult struct {
	Success *JoinResponse `thrift:"success,0,optional" frugal:"0,optional,JoinResponse" json:"success,omitempty"`
}

func NewServiceLeaveResult() *ServiceLeaveResult {
	return &ServiceLeaveResult{}
}

func (p *ServiceLeaveResult) InitDefault() {
}

var ServiceLeaveResult_Success_DEFAULT *JoinResponse

func (p *ServiceLeaveResult) GetSuccess() (v *JoinResponse) {
	if !p.IsSetSuccess() {
		return ServiceLeaveResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServiceLeaveResult) SetSuccess(x interface{}) {
	p.Success = x.(*JoinResponse)
}

func (p *ServiceLeaveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServiceLeaveResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceLeaveResult(%+v)", *p)
}

var fieldIDToName_ServiceLeaveResult = map[int16]string{
	0: "success",
}

type ServicePublishArgs struct {
	Req *PublishRequest `thrift:"req,1" frugal:"1,default,PublishRequest" json:"req"`
}

func NewServicePublishArgs() *ServicePublishArgs {
	return &ServicePublishArgs{}
}

func (p *ServicePublishArgs) InitDefault() {
}

var ServicePublishArgs_Req_DEFAULT *PublishRequest

func (p *ServicePublishArgs) GetReq() (v *PublishRequest) {
	if !p.IsSetReq() {
		return ServicePublishArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServicePublishArgs) SetReq(val *PublishRequest) {
	p.Req = val
}

func (p *ServicePublishArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServicePublishArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServicePublishArgs(%+v)", *p)
}

var fieldIDToName_ServicePublishArgs = map[int16]string{
	1: "req",
}

type ServicePublishResult struct {
}

func NewServicePublishResult() *ServicePublishResult {
	return &ServicePublishResult{}
}

func (p *ServicePublishResult) InitDefault() {
}

func (p *ServicePublishResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServicePublishResult(%+v)", *p)
}

var fieldIDToName_ServicePublishResult = map[int16]string{}
