// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cluster/pb/peer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / An empty message.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cluster_pb_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{0}
}

// / IsOnlineReq is the request message for IsOnline RPC.
type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       map[string]string      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_cluster_pb_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{1}
}

func (x *IsOnlineReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / IsOnlineResp is the response message for IsOnline RPC.
type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_cluster_pb_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{2}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// / MessageReq is the request message for SendToClients RPC.
type MessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Targets       map[string]string      `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReq) Reset() {
	*x = MessageReq{}
	mi := &file_cluster_pb_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReq) ProtoMessage() {}

func (x *MessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReq.ProtoReflect.Descriptor instead.
func (*MessageReq) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{3}
}

func (x *MessageReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / MessageResp is the response message for SendMessage RPC.
type MessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResp) Reset() {
	*x = MessageResp{}
	mi := &file_cluster_pb_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResp) ProtoMessage() {}

func (x *MessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResp.ProtoReflect.Descriptor instead.
func (*MessageResp) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{4}
}

func (x *MessageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// / KickConnReq is the request message for KickUser RPC.
type KickConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       map[string]string      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnReq) Reset() {
	*x = KickConnReq{}
	mi := &file_cluster_pb_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnReq) ProtoMessage() {}

func (x *KickConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnReq.ProtoReflect.Descriptor instead.
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{5}
}

func (x *KickConnReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// RaftMessage represents a Raft message
type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft message data in binary format
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_cluster_pb_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{6}
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// / Progress represents the progress of raft node.
type RaftProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         uint64                 `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	Next          uint64                 `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftProgress) Reset() {
	*x = RaftProgress{}
	mi := &file_cluster_pb_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftProgress) ProtoMessage() {}

func (x *RaftProgress) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftProgress.ProtoReflect.Descriptor instead.
func (*RaftProgress) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{7}
}

func (x *RaftProgress) GetMatch() uint64 {
	if x != nil {
		return x.Match
	}
	return 0
}

func (x *RaftProgress) GetNext() uint64 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *RaftProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// / Inspects is the response message for Inspect RPC.
type Status struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            uint64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftTerm      uint64                   `protobuf:"varint,2,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	RaftState     string                   `protobuf:"bytes,3,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	RaftApplied   uint64                   `protobuf:"varint,4,opt,name=raft_applied,json=raftApplied,proto3" json:"raft_applied,omitempty"`
	RaftLogSize   uint64                   `protobuf:"varint,5,opt,name=raft_log_size,json=raftLogSize,proto3" json:"raft_log_size,omitempty"`
	RaftNodeCount int32                    `protobuf:"varint,6,opt,name=raft_node_count,json=raftNodeCount,proto3" json:"raft_node_count,omitempty"`
	UserCount     map[uint64]int32         `protobuf:"bytes,7,rep,name=user_count,json=userCount,proto3" json:"user_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClientCount   map[string]int32         `protobuf:"bytes,8,rep,name=client_count,json=clientCount,proto3" json:"client_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ChannelCount  map[uint64]int32         `protobuf:"bytes,9,rep,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RaftProgress  map[uint64]*RaftProgress `protobuf:"bytes,10,rep,name=raft_progress,json=raftProgress,proto3" json:"raft_progress,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_cluster_pb_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{8}
}

func (x *Status) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Status) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *Status) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *Status) GetRaftApplied() uint64 {
	if x != nil {
		return x.RaftApplied
	}
	return 0
}

func (x *Status) GetRaftLogSize() uint64 {
	if x != nil {
		return x.RaftLogSize
	}
	return 0
}

func (x *Status) GetRaftNodeCount() int32 {
	if x != nil {
		return x.RaftNodeCount
	}
	return 0
}

func (x *Status) GetUserCount() map[uint64]int32 {
	if x != nil {
		return x.UserCount
	}
	return nil
}

func (x *Status) GetClientCount() map[string]int32 {
	if x != nil {
		return x.ClientCount
	}
	return nil
}

func (x *Status) GetChannelCount() map[uint64]int32 {
	if x != nil {
		return x.ChannelCount
	}
	return nil
}

func (x *Status) GetRaftProgress() map[uint64]*RaftProgress {
	if x != nil {
		return x.RaftProgress
	}
	return nil
}

type StartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	mi := &file_cluster_pb_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_pb_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_cluster_pb_peer_proto_rawDescGZIP(), []int{9}
}

func (x *StartReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

var File_cluster_pb_peer_proto protoreflect.FileDescriptor

const file_cluster_pb_peer_proto_rawDesc = "" +
	"\n" +
	"\x15cluster/pb/peer.proto\x12\x02pb\"\a\n" +
	"\x05Empty\"\x81\x01\n" +
	"\vIsOnlineReq\x126\n" +
	"\atargets\x18\x01 \x03(\v2\x1c.pb.IsOnlineReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"\x99\x01\n" +
	"\n" +
	"MessageReq\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x125\n" +
	"\atargets\x18\x02 \x03(\v2\x1b.pb.MessageReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\vMessageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\"\x81\x01\n" +
	"\vKickConnReq\x126\n" +
	"\atargets\x18\x01 \x03(\v2\x1c.pb.KickConnReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"N\n" +
	"\fRaftProgress\x12\x14\n" +
	"\x05match\x18\x01 \x01(\x04R\x05match\x12\x12\n" +
	"\x04next\x18\x02 \x01(\x04R\x04next\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\xd5\x05\n" +
	"\x06Status\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\traft_term\x18\x02 \x01(\x04R\braftTerm\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x03 \x01(\tR\traftState\x12!\n" +
	"\fraft_applied\x18\x04 \x01(\x04R\vraftApplied\x12\"\n" +
	"\rraft_log_size\x18\x05 \x01(\x04R\vraftLogSize\x12&\n" +
	"\x0fraft_node_count\x18\x06 \x01(\x05R\rraftNodeCount\x128\n" +
	"\n" +
	"user_count\x18\a \x03(\v2\x19.pb.Status.UserCountEntryR\tuserCount\x12>\n" +
	"\fclient_count\x18\b \x03(\v2\x1b.pb.Status.ClientCountEntryR\vclientCount\x12A\n" +
	"\rchannel_count\x18\t \x03(\v2\x1c.pb.Status.ChannelCountEntryR\fchannelCount\x12A\n" +
	"\rraft_progress\x18\n" +
	" \x03(\v2\x1c.pb.Status.RaftProgressEntryR\fraftProgress\x1a<\n" +
	"\x0eUserCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10ClientCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11ChannelCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aQ\n" +
	"\x11RaftProgressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.pb.RaftProgressR\x05value:\x028\x01\"$\n" +
	"\bStartReq\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork2\xa9\x03\n" +
	"\vPeerService\x12\"\n" +
	"\aInspect\x12\t.pb.Empty\x1a\n" +
	".pb.Status\"\x00\x12/\n" +
	"\bIsOnline\x12\x0f.pb.IsOnlineReq\x1a\x10.pb.IsOnlineResp\"\x00\x12(\n" +
	"\bKickConn\x12\x0f.pb.KickConnReq\x1a\t.pb.Empty\"\x00\x12.\n" +
	"\tSendToAll\x12\x0e.pb.MessageReq\x1a\x0f.pb.MessageResp\"\x00\x12/\n" +
	"\n" +
	"SendToUser\x12\x0e.pb.MessageReq\x1a\x0f.pb.MessageResp\"\x00\x122\n" +
	"\rSendToChannel\x12\x0e.pb.MessageReq\x1a\x0f.pb.MessageResp\"\x00\x12/\n" +
	"\x0fSendRaftMessage\x12\x0f.pb.RaftMessage\x1a\t.pb.Empty\"\x00\x12*\n" +
	"\rStartListener\x12\f.pb.StartReq\x1a\t.pb.Empty\"\x00\x12)\n" +
	"\fStopListener\x12\f.pb.StartReq\x1a\t.pb.Empty\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_cluster_pb_peer_proto_rawDescOnce sync.Once
	file_cluster_pb_peer_proto_rawDescData []byte
)

func file_cluster_pb_peer_proto_rawDescGZIP() []byte {
	file_cluster_pb_peer_proto_rawDescOnce.Do(func() {
		file_cluster_pb_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_pb_peer_proto_rawDesc), len(file_cluster_pb_peer_proto_rawDesc)))
	})
	return file_cluster_pb_peer_proto_rawDescData
}

var file_cluster_pb_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cluster_pb_peer_proto_goTypes = []any{
	(*Empty)(nil),        // 0: pb.Empty
	(*IsOnlineReq)(nil),  // 1: pb.IsOnlineReq
	(*IsOnlineResp)(nil), // 2: pb.IsOnlineResp
	(*MessageReq)(nil),   // 3: pb.MessageReq
	(*MessageResp)(nil),  // 4: pb.MessageResp
	(*KickConnReq)(nil),  // 5: pb.KickConnReq
	(*RaftMessage)(nil),  // 6: pb.RaftMessage
	(*RaftProgress)(nil), // 7: pb.RaftProgress
	(*Status)(nil),       // 8: pb.Status
	(*StartReq)(nil),     // 9: pb.StartReq
	nil,                  // 10: pb.IsOnlineReq.TargetsEntry
	nil,                  // 11: pb.MessageReq.TargetsEntry
	nil,                  // 12: pb.KickConnReq.TargetsEntry
	nil,                  // 13: pb.Status.UserCountEntry
	nil,                  // 14: pb.Status.ClientCountEntry
	nil,                  // 15: pb.Status.ChannelCountEntry
	nil,                  // 16: pb.Status.RaftProgressEntry
}
var file_cluster_pb_peer_proto_depIdxs = []int32{
	10, // 0: pb.IsOnlineReq.targets:type_name -> pb.IsOnlineReq.TargetsEntry
	11, // 1: pb.MessageReq.targets:type_name -> pb.MessageReq.TargetsEntry
	12, // 2: pb.KickConnReq.targets:type_name -> pb.KickConnReq.TargetsEntry
	13, // 3: pb.Status.user_count:type_name -> pb.Status.UserCountEntry
	14, // 4: pb.Status.client_count:type_name -> pb.Status.ClientCountEntry
	15, // 5: pb.Status.channel_count:type_name -> pb.Status.ChannelCountEntry
	16, // 6: pb.Status.raft_progress:type_name -> pb.Status.RaftProgressEntry
	7,  // 7: pb.Status.RaftProgressEntry.value:type_name -> pb.RaftProgress
	0,  // 8: pb.PeerService.Inspect:input_type -> pb.Empty
	1,  // 9: pb.PeerService.IsOnline:input_type -> pb.IsOnlineReq
	5,  // 10: pb.PeerService.KickConn:input_type -> pb.KickConnReq
	3,  // 11: pb.PeerService.SendToAll:input_type -> pb.MessageReq
	3,  // 12: pb.PeerService.SendToUser:input_type -> pb.MessageReq
	3,  // 13: pb.PeerService.SendToChannel:input_type -> pb.MessageReq
	6,  // 14: pb.PeerService.SendRaftMessage:input_type -> pb.RaftMessage
	9,  // 15: pb.PeerService.StartListener:input_type -> pb.StartReq
	9,  // 16: pb.PeerService.StopListener:input_type -> pb.StartReq
	8,  // 17: pb.PeerService.Inspect:output_type -> pb.Status
	2,  // 18: pb.PeerService.IsOnline:output_type -> pb.IsOnlineResp
	0,  // 19: pb.PeerService.KickConn:output_type -> pb.Empty
	4,  // 20: pb.PeerService.SendToAll:output_type -> pb.MessageResp
	4,  // 21: pb.PeerService.SendToUser:output_type -> pb.MessageResp
	4,  // 22: pb.PeerService.SendToChannel:output_type -> pb.MessageResp
	0,  // 23: pb.PeerService.SendRaftMessage:output_type -> pb.Empty
	0,  // 24: pb.PeerService.StartListener:output_type -> pb.Empty
	0,  // 25: pb.PeerService.StopListener:output_type -> pb.Empty
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cluster_pb_peer_proto_init() }
func file_cluster_pb_peer_proto_init() {
	if File_cluster_pb_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_pb_peer_proto_rawDesc), len(file_cluster_pb_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_pb_peer_proto_goTypes,
		DependencyIndexes: file_cluster_pb_peer_proto_depIdxs,
		MessageInfos:      file_cluster_pb_peer_proto_msgTypes,
	}.Build()
	File_cluster_pb_peer_proto = out.File
	file_cluster_pb_peer_proto_goTypes = nil
	file_cluster_pb_peer_proto_depIdxs = nil
}
