// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broker/protos/peer.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / An empty message.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{0}
}

// / IsOnlineReq is the request message for IsOnline RPC.
type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       map[string]string      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{1}
}

func (x *IsOnlineReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / IsOnlineResp is the response message for IsOnline RPC.
type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{2}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// / MessageReq is the request message for SendToClients RPC.
type MessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Targets       map[string]string      `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReq) Reset() {
	*x = MessageReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReq) ProtoMessage() {}

func (x *MessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReq.ProtoReflect.Descriptor instead.
func (*MessageReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{3}
}

func (x *MessageReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / MessageResp is the response message for SendMessage RPC.
type MessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResp) Reset() {
	*x = MessageResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResp) ProtoMessage() {}

func (x *MessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResp.ProtoReflect.Descriptor instead.
func (*MessageResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{4}
}

func (x *MessageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// / KickConnReq is the request message for KickUser RPC.
type KickConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       map[string]string      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnReq) Reset() {
	*x = KickConnReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnReq) ProtoMessage() {}

func (x *KickConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnReq.ProtoReflect.Descriptor instead.
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{5}
}

func (x *KickConnReq) GetTargets() map[string]string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// RaftMessage represents a Raft message
type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft message data in binary format
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{6}
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// / Progress represents the progress of raft node.
type RaftProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         uint64                 `protobuf:"varint,2,opt,name=match,proto3" json:"match,omitempty"`
	Next          uint64                 `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftProgress) Reset() {
	*x = RaftProgress{}
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftProgress) ProtoMessage() {}

func (x *RaftProgress) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftProgress.ProtoReflect.Descriptor instead.
func (*RaftProgress) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{7}
}

func (x *RaftProgress) GetMatch() uint64 {
	if x != nil {
		return x.Match
	}
	return 0
}

func (x *RaftProgress) GetNext() uint64 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *RaftProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// / Inspects is the response message for Inspect RPC.
type Status struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            uint64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftState     string                   `protobuf:"bytes,2,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	RaftTerm      uint64                   `protobuf:"varint,3,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	RaftApplied   uint64                   `protobuf:"varint,4,opt,name=raft_applied,json=raftApplied,proto3" json:"raft_applied,omitempty"`
	RaftLogSize   uint64                   `protobuf:"varint,5,opt,name=raft_log_size,json=raftLogSize,proto3" json:"raft_log_size,omitempty"`
	ClientCount   int32                    `protobuf:"varint,6,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	ClusterSize   int32                    `protobuf:"varint,7,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	UserCount     map[uint64]int32         `protobuf:"bytes,8,rep,name=user_count,json=userCount,proto3" json:"user_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ChannelCount  map[uint64]int32         `protobuf:"bytes,9,rep,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RaftProgress  map[uint64]*RaftProgress `protobuf:"bytes,10,rep,name=raft_progress,json=raftProgress,proto3" json:"raft_progress,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{8}
}

func (x *Status) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Status) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *Status) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *Status) GetRaftApplied() uint64 {
	if x != nil {
		return x.RaftApplied
	}
	return 0
}

func (x *Status) GetRaftLogSize() uint64 {
	if x != nil {
		return x.RaftLogSize
	}
	return 0
}

func (x *Status) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *Status) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *Status) GetUserCount() map[uint64]int32 {
	if x != nil {
		return x.UserCount
	}
	return nil
}

func (x *Status) GetChannelCount() map[uint64]int32 {
	if x != nil {
		return x.ChannelCount
	}
	return nil
}

func (x *Status) GetRaftProgress() map[uint64]*RaftProgress {
	if x != nil {
		return x.RaftProgress
	}
	return nil
}

var File_broker_protos_peer_proto protoreflect.FileDescriptor

const file_broker_protos_peer_proto_rawDesc = "" +
	"\n" +
	"\x18broker/protos/peer.proto\x12\x06protos\"\a\n" +
	"\x05Empty\"\x85\x01\n" +
	"\vIsOnlineReq\x12:\n" +
	"\atargets\x18\x01 \x03(\v2 .protos.IsOnlineReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"\x9d\x01\n" +
	"\n" +
	"MessageReq\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x129\n" +
	"\atargets\x18\x04 \x03(\v2\x1f.protos.MessageReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\vMessageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\"\x85\x01\n" +
	"\vKickConnReq\x12:\n" +
	"\atargets\x18\x01 \x03(\v2 .protos.KickConnReq.TargetsEntryR\atargets\x1a:\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"N\n" +
	"\fRaftProgress\x12\x14\n" +
	"\x05match\x18\x02 \x01(\x04R\x05match\x12\x12\n" +
	"\x04next\x18\x03 \x01(\x04R\x04next\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\x83\x05\n" +
	"\x06Status\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x02 \x01(\tR\traftState\x12\x1b\n" +
	"\traft_term\x18\x03 \x01(\x04R\braftTerm\x12!\n" +
	"\fraft_applied\x18\x04 \x01(\x04R\vraftApplied\x12\"\n" +
	"\rraft_log_size\x18\x05 \x01(\x04R\vraftLogSize\x12!\n" +
	"\fclient_count\x18\x06 \x01(\x05R\vclientCount\x12!\n" +
	"\fcluster_size\x18\a \x01(\x05R\vclusterSize\x12<\n" +
	"\n" +
	"user_count\x18\b \x03(\v2\x1d.protos.Status.UserCountEntryR\tuserCount\x12E\n" +
	"\rchannel_count\x18\t \x03(\v2 .protos.Status.ChannelCountEntryR\fchannelCount\x12E\n" +
	"\rraft_progress\x18\n" +
	" \x03(\v2 .protos.Status.RaftProgressEntryR\fraftProgress\x1a<\n" +
	"\x0eUserCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11ChannelCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aU\n" +
	"\x11RaftProgressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protos.RaftProgressR\x05value:\x028\x012\xd1\x02\n" +
	"\vPeerService\x12*\n" +
	"\aInspect\x12\r.protos.Empty\x1a\x0e.protos.Status\"\x00\x127\n" +
	"\bIsOnline\x12\x13.protos.IsOnlineReq\x1a\x14.protos.IsOnlineResp\"\x00\x120\n" +
	"\bKickConn\x12\x13.protos.KickConnReq\x1a\r.protos.Empty\"\x00\x126\n" +
	"\tSendToAll\x12\x12.protos.MessageReq\x1a\x13.protos.MessageResp\"\x00\x12:\n" +
	"\rSendToTargets\x12\x12.protos.MessageReq\x1a\x13.protos.MessageResp\"\x00\x127\n" +
	"\x0fSendRaftMessage\x12\x13.protos.RaftMessage\x1a\r.protos.Empty\"\x00B\n" +
	"Z\b./protosb\x06proto3"

var (
	file_broker_protos_peer_proto_rawDescOnce sync.Once
	file_broker_protos_peer_proto_rawDescData []byte
)

func file_broker_protos_peer_proto_rawDescGZIP() []byte {
	file_broker_protos_peer_proto_rawDescOnce.Do(func() {
		file_broker_protos_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)))
	})
	return file_broker_protos_peer_proto_rawDescData
}

var file_broker_protos_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_broker_protos_peer_proto_goTypes = []any{
	(*Empty)(nil),        // 0: protos.Empty
	(*IsOnlineReq)(nil),  // 1: protos.IsOnlineReq
	(*IsOnlineResp)(nil), // 2: protos.IsOnlineResp
	(*MessageReq)(nil),   // 3: protos.MessageReq
	(*MessageResp)(nil),  // 4: protos.MessageResp
	(*KickConnReq)(nil),  // 5: protos.KickConnReq
	(*RaftMessage)(nil),  // 6: protos.RaftMessage
	(*RaftProgress)(nil), // 7: protos.RaftProgress
	(*Status)(nil),       // 8: protos.Status
	nil,                  // 9: protos.IsOnlineReq.TargetsEntry
	nil,                  // 10: protos.MessageReq.TargetsEntry
	nil,                  // 11: protos.KickConnReq.TargetsEntry
	nil,                  // 12: protos.Status.UserCountEntry
	nil,                  // 13: protos.Status.ChannelCountEntry
	nil,                  // 14: protos.Status.RaftProgressEntry
}
var file_broker_protos_peer_proto_depIdxs = []int32{
	9,  // 0: protos.IsOnlineReq.targets:type_name -> protos.IsOnlineReq.TargetsEntry
	10, // 1: protos.MessageReq.targets:type_name -> protos.MessageReq.TargetsEntry
	11, // 2: protos.KickConnReq.targets:type_name -> protos.KickConnReq.TargetsEntry
	12, // 3: protos.Status.user_count:type_name -> protos.Status.UserCountEntry
	13, // 4: protos.Status.channel_count:type_name -> protos.Status.ChannelCountEntry
	14, // 5: protos.Status.raft_progress:type_name -> protos.Status.RaftProgressEntry
	7,  // 6: protos.Status.RaftProgressEntry.value:type_name -> protos.RaftProgress
	0,  // 7: protos.PeerService.Inspect:input_type -> protos.Empty
	1,  // 8: protos.PeerService.IsOnline:input_type -> protos.IsOnlineReq
	5,  // 9: protos.PeerService.KickConn:input_type -> protos.KickConnReq
	3,  // 10: protos.PeerService.SendToAll:input_type -> protos.MessageReq
	3,  // 11: protos.PeerService.SendToTargets:input_type -> protos.MessageReq
	6,  // 12: protos.PeerService.SendRaftMessage:input_type -> protos.RaftMessage
	8,  // 13: protos.PeerService.Inspect:output_type -> protos.Status
	2,  // 14: protos.PeerService.IsOnline:output_type -> protos.IsOnlineResp
	0,  // 15: protos.PeerService.KickConn:output_type -> protos.Empty
	4,  // 16: protos.PeerService.SendToAll:output_type -> protos.MessageResp
	4,  // 17: protos.PeerService.SendToTargets:output_type -> protos.MessageResp
	0,  // 18: protos.PeerService.SendRaftMessage:output_type -> protos.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_broker_protos_peer_proto_init() }
func file_broker_protos_peer_proto_init() {
	if File_broker_protos_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broker_protos_peer_proto_goTypes,
		DependencyIndexes: file_broker_protos_peer_proto_depIdxs,
		MessageInfos:      file_broker_protos_peer_proto_msgTypes,
	}.Build()
	File_broker_protos_peer_proto = out.File
	file_broker_protos_peer_proto_goTypes = nil
	file_broker_protos_peer_proto_depIdxs = nil
}
