// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: broker/protos/peer.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerService_Inspect_FullMethodName         = "/protos.PeerService/Inspect"
	PeerService_IsOnline_FullMethodName        = "/protos.PeerService/IsOnline"
	PeerService_KickConn_FullMethodName        = "/protos.PeerService/KickConn"
	PeerService_SendToAll_FullMethodName       = "/protos.PeerService/SendToAll"
	PeerService_SendToTargets_FullMethodName   = "/protos.PeerService/SendToTargets"
	PeerService_UserOpened_FullMethodName      = "/protos.PeerService/UserOpened"
	PeerService_UserClosed_FullMethodName      = "/protos.PeerService/UserClosed"
	PeerService_SendRaftMessage_FullMethodName = "/protos.PeerService/SendRaftMessage"
)

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type PeerServiceClient interface {
	// Inspect provides peer inspection info.
	// For example: user count, client count, cluster size, channel count.
	// It is mainly used for monitoring and debugging.
	Inspect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Inspects, error)
	// IsOnline checks if a user is online.
	IsOnline(ctx context.Context, in *IsOnlineReq, opts ...grpc.CallOption) (*IsOnlineResp, error)
	// KickConn kicks a connection by connection ID.
	KickConn(ctx context.Context, in *KickConnReq, opts ...grpc.CallOption) (*Empty, error)
	// SendMessage sends a message to a user or a channel.
	SendToAll(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageResp, error)
	// SendToTargets sends a message to a channel.
	SendToTargets(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageResp, error)
	// UserOpened is called when a user opens a connection.
	UserOpened(ctx context.Context, in *UserOpenedReq, opts ...grpc.CallOption) (*Empty, error)
	// UserClosed is called when a user closes a connection.
	UserClosed(ctx context.Context, in *UserClosedReq, opts ...grpc.CallOption) (*Empty, error)
	// JoinChannel adds a user to the specified channels.
	// rpc JoinChannel (ChannelReq) returns (ChannelResp) {}
	// // LeaveChannel removes a user from the specified channels.
	// rpc LeaveChannel (ChannelReq) returns (ChannelResp) {}
	// -------------------- Raft 相关方法 --------------------
	// SendRaftMessage handles a Raft message from another node
	SendRaftMessage(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*Empty, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) Inspect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Inspects, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inspects)
	err := c.cc.Invoke(ctx, PeerService_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) IsOnline(ctx context.Context, in *IsOnlineReq, opts ...grpc.CallOption) (*IsOnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsOnlineResp)
	err := c.cc.Invoke(ctx, PeerService_IsOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) KickConn(ctx context.Context, in *KickConnReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PeerService_KickConn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) SendToAll(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResp)
	err := c.cc.Invoke(ctx, PeerService_SendToAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) SendToTargets(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResp)
	err := c.cc.Invoke(ctx, PeerService_SendToTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) UserOpened(ctx context.Context, in *UserOpenedReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PeerService_UserOpened_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) UserClosed(ctx context.Context, in *UserClosedReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PeerService_UserClosed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) SendRaftMessage(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PeerService_SendRaftMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility.
//
// The greeting service definition.
type PeerServiceServer interface {
	// Inspect provides peer inspection info.
	// For example: user count, client count, cluster size, channel count.
	// It is mainly used for monitoring and debugging.
	Inspect(context.Context, *Empty) (*Inspects, error)
	// IsOnline checks if a user is online.
	IsOnline(context.Context, *IsOnlineReq) (*IsOnlineResp, error)
	// KickConn kicks a connection by connection ID.
	KickConn(context.Context, *KickConnReq) (*Empty, error)
	// SendMessage sends a message to a user or a channel.
	SendToAll(context.Context, *MessageReq) (*MessageResp, error)
	// SendToTargets sends a message to a channel.
	SendToTargets(context.Context, *MessageReq) (*MessageResp, error)
	// UserOpened is called when a user opens a connection.
	UserOpened(context.Context, *UserOpenedReq) (*Empty, error)
	// UserClosed is called when a user closes a connection.
	UserClosed(context.Context, *UserClosedReq) (*Empty, error)
	// JoinChannel adds a user to the specified channels.
	// rpc JoinChannel (ChannelReq) returns (ChannelResp) {}
	// // LeaveChannel removes a user from the specified channels.
	// rpc LeaveChannel (ChannelReq) returns (ChannelResp) {}
	// -------------------- Raft 相关方法 --------------------
	// SendRaftMessage handles a Raft message from another node
	SendRaftMessage(context.Context, *RaftMessage) (*Empty, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerServiceServer struct{}

func (UnimplementedPeerServiceServer) Inspect(context.Context, *Empty) (*Inspects, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedPeerServiceServer) IsOnline(context.Context, *IsOnlineReq) (*IsOnlineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsOnline not implemented")
}
func (UnimplementedPeerServiceServer) KickConn(context.Context, *KickConnReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickConn not implemented")
}
func (UnimplementedPeerServiceServer) SendToAll(context.Context, *MessageReq) (*MessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToAll not implemented")
}
func (UnimplementedPeerServiceServer) SendToTargets(context.Context, *MessageReq) (*MessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToTargets not implemented")
}
func (UnimplementedPeerServiceServer) UserOpened(context.Context, *UserOpenedReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOpened not implemented")
}
func (UnimplementedPeerServiceServer) UserClosed(context.Context, *UserClosedReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClosed not implemented")
}
func (UnimplementedPeerServiceServer) SendRaftMessage(context.Context, *RaftMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRaftMessage not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}
func (UnimplementedPeerServiceServer) testEmbeddedByValue()                     {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerService_ServiceDesc, srv)
}

func _PeerService_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Inspect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_IsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).IsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_IsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).IsOnline(ctx, req.(*IsOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_KickConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickConnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).KickConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_KickConn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).KickConn(ctx, req.(*KickConnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_SendToAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).SendToAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_SendToAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).SendToAll(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_SendToTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).SendToTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_SendToTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).SendToTargets(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_UserOpened_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOpenedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).UserOpened(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_UserOpened_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).UserOpened(ctx, req.(*UserOpenedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_UserClosed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClosedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).UserClosed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_UserClosed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).UserClosed(ctx, req.(*UserClosedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_SendRaftMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).SendRaftMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_SendRaftMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).SendRaftMessage(ctx, req.(*RaftMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerService_ServiceDesc is the grpc.ServiceDesc for PeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspect",
			Handler:    _PeerService_Inspect_Handler,
		},
		{
			MethodName: "IsOnline",
			Handler:    _PeerService_IsOnline_Handler,
		},
		{
			MethodName: "KickConn",
			Handler:    _PeerService_KickConn_Handler,
		},
		{
			MethodName: "SendToAll",
			Handler:    _PeerService_SendToAll_Handler,
		},
		{
			MethodName: "SendToTargets",
			Handler:    _PeerService_SendToTargets_Handler,
		},
		{
			MethodName: "UserOpened",
			Handler:    _PeerService_UserOpened_Handler,
		},
		{
			MethodName: "UserClosed",
			Handler:    _PeerService_UserClosed_Handler,
		},
		{
			MethodName: "SendRaftMessage",
			Handler:    _PeerService_SendRaftMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker/protos/peer.proto",
}
