// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broker/protos/peer.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{0}
}

type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{1}
}

func (x *IsOnlineReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{2}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          int32                  `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageReq) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *SendMessageReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendMessageReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SendMessageResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{5}
}

func (x *KickUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type KickConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnReq) Reset() {
	*x = KickConnReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnReq) ProtoMessage() {}

func (x *KickConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnReq.ProtoReflect.Descriptor instead.
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{6}
}

func (x *KickConnReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type Inspects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserCount     int32                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	ClientCount   int32                  `protobuf:"varint,3,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	ClusterSize   int32                  `protobuf:"varint,4,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	ChannelCount  int32                  `protobuf:"varint,5,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inspects) Reset() {
	*x = Inspects{}
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inspects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inspects) ProtoMessage() {}

func (x *Inspects) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inspects.ProtoReflect.Descriptor instead.
func (*Inspects) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{7}
}

func (x *Inspects) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inspects) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Inspects) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *Inspects) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *Inspects) GetChannelCount() int32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

type ChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Channels      []string               `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelReq) Reset() {
	*x = ChannelReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelReq) ProtoMessage() {}

func (x *ChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelReq.ProtoReflect.Descriptor instead.
func (*ChannelReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChannelReq) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResp) Reset() {
	*x = ChannelResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResp) ProtoMessage() {}

func (x *ChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResp.ProtoReflect.Descriptor instead.
func (*ChannelResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_broker_protos_peer_proto protoreflect.FileDescriptor

const file_broker_protos_peer_proto_rawDesc = "" +
	"\n" +
	"\x18broker/protos/peer.proto\x12\x06protos\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\vIsOnlineReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"V\n" +
	"\x0eSendMessageReq\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\x05R\x04flag\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"A\n" +
	"\x0fSendMessageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\"\x1f\n" +
	"\vKickUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\x1f\n" +
	"\vKickConnReq\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"\xa4\x01\n" +
	"\bInspects\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x05R\tuserCount\x12!\n" +
	"\fclient_count\x18\x03 \x01(\x05R\vclientCount\x12!\n" +
	"\fcluster_size\x18\x04 \x01(\x05R\vclusterSize\x12#\n" +
	"\rchannel_count\x18\x05 \x01(\x05R\fchannelCount\":\n" +
	"\n" +
	"ChannelReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\"#\n" +
	"\vChannelResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\x8f\x03\n" +
	"\vPeerService\x12,\n" +
	"\aInspect\x12\r.protos.Empty\x1a\x10.protos.Inspects\"\x00\x127\n" +
	"\bIsOnline\x12\x13.protos.IsOnlineReq\x1a\x14.protos.IsOnlineResp\"\x00\x120\n" +
	"\bKickUser\x12\x13.protos.KickUserReq\x1a\r.protos.Empty\"\x00\x120\n" +
	"\bKickConn\x12\x13.protos.KickConnReq\x1a\r.protos.Empty\"\x00\x12@\n" +
	"\vSendMessage\x12\x16.protos.SendMessageReq\x1a\x17.protos.SendMessageResp\"\x00\x128\n" +
	"\vJoinChannel\x12\x12.protos.ChannelReq\x1a\x13.protos.ChannelResp\"\x00\x129\n" +
	"\fLeaveChannel\x12\x12.protos.ChannelReq\x1a\x13.protos.ChannelResp\"\x00B\n" +
	"Z\b./protosb\x06proto3"

var (
	file_broker_protos_peer_proto_rawDescOnce sync.Once
	file_broker_protos_peer_proto_rawDescData []byte
)

func file_broker_protos_peer_proto_rawDescGZIP() []byte {
	file_broker_protos_peer_proto_rawDescOnce.Do(func() {
		file_broker_protos_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)))
	})
	return file_broker_protos_peer_proto_rawDescData
}

var file_broker_protos_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_broker_protos_peer_proto_goTypes = []any{
	(*Empty)(nil),           // 0: protos.Empty
	(*IsOnlineReq)(nil),     // 1: protos.IsOnlineReq
	(*IsOnlineResp)(nil),    // 2: protos.IsOnlineResp
	(*SendMessageReq)(nil),  // 3: protos.SendMessageReq
	(*SendMessageResp)(nil), // 4: protos.SendMessageResp
	(*KickUserReq)(nil),     // 5: protos.KickUserReq
	(*KickConnReq)(nil),     // 6: protos.KickConnReq
	(*Inspects)(nil),        // 7: protos.Inspects
	(*ChannelReq)(nil),      // 8: protos.ChannelReq
	(*ChannelResp)(nil),     // 9: protos.ChannelResp
}
var file_broker_protos_peer_proto_depIdxs = []int32{
	0, // 0: protos.PeerService.Inspect:input_type -> protos.Empty
	1, // 1: protos.PeerService.IsOnline:input_type -> protos.IsOnlineReq
	5, // 2: protos.PeerService.KickUser:input_type -> protos.KickUserReq
	6, // 3: protos.PeerService.KickConn:input_type -> protos.KickConnReq
	3, // 4: protos.PeerService.SendMessage:input_type -> protos.SendMessageReq
	8, // 5: protos.PeerService.JoinChannel:input_type -> protos.ChannelReq
	8, // 6: protos.PeerService.LeaveChannel:input_type -> protos.ChannelReq
	7, // 7: protos.PeerService.Inspect:output_type -> protos.Inspects
	2, // 8: protos.PeerService.IsOnline:output_type -> protos.IsOnlineResp
	0, // 9: protos.PeerService.KickUser:output_type -> protos.Empty
	0, // 10: protos.PeerService.KickConn:output_type -> protos.Empty
	4, // 11: protos.PeerService.SendMessage:output_type -> protos.SendMessageResp
	9, // 12: protos.PeerService.JoinChannel:output_type -> protos.ChannelResp
	9, // 13: protos.PeerService.LeaveChannel:output_type -> protos.ChannelResp
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broker_protos_peer_proto_init() }
func file_broker_protos_peer_proto_init() {
	if File_broker_protos_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broker_protos_peer_proto_goTypes,
		DependencyIndexes: file_broker_protos_peer_proto_depIdxs,
		MessageInfos:      file_broker_protos_peer_proto_msgTypes,
	}.Build()
	File_broker_protos_peer_proto = out.File
	file_broker_protos_peer_proto_goTypes = nil
	file_broker_protos_peer_proto_depIdxs = nil
}
