// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broker/protos/peer.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / An empty message.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{0}
}

// / Target represents a message target
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Net           string                 `protobuf:"bytes,2,opt,name=net,proto3" json:"net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Target) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

// / IsOnlineReq is the request message for IsOnline RPC.
type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{2}
}

func (x *IsOnlineReq) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / IsOnlineResp is the response message for IsOnline RPC.
type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{3}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// / MessageReq is the request message for SendToClients RPC.
type MessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Targets       []*Target              `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReq) Reset() {
	*x = MessageReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReq) ProtoMessage() {}

func (x *MessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReq.ProtoReflect.Descriptor instead.
func (*MessageReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{4}
}

func (x *MessageReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageReq) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / MessageResp is the response message for SendMessage RPC.
type MessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResp) Reset() {
	*x = MessageResp{}
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResp) ProtoMessage() {}

func (x *MessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResp.ProtoReflect.Descriptor instead.
func (*MessageResp) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{5}
}

func (x *MessageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// / KickConnReq is the request message for KickUser RPC.
type KickConnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickConnReq) Reset() {
	*x = KickConnReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickConnReq) ProtoMessage() {}

func (x *KickConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickConnReq.ProtoReflect.Descriptor instead.
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{6}
}

func (x *KickConnReq) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// / Inspects is the response message for Inspect RPC.
type Inspects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserCount     int32                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	ClientCount   int32                  `protobuf:"varint,3,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	ClusterSize   int32                  `protobuf:"varint,4,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	ChannelCount  int32                  `protobuf:"varint,5,opt,name=channel_count,json=channelCount,proto3" json:"channel_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inspects) Reset() {
	*x = Inspects{}
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inspects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inspects) ProtoMessage() {}

func (x *Inspects) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inspects.ProtoReflect.Descriptor instead.
func (*Inspects) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{7}
}

func (x *Inspects) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inspects) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Inspects) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *Inspects) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *Inspects) GetChannelCount() int32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

// UserOpenedReq is the request message for UserOpened RPC.
type UserOpenedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Net           string                 `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOpenedReq) Reset() {
	*x = UserOpenedReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOpenedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOpenedReq) ProtoMessage() {}

func (x *UserOpenedReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOpenedReq.ProtoReflect.Descriptor instead.
func (*UserOpenedReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{8}
}

func (x *UserOpenedReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserOpenedReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *UserOpenedReq) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *UserOpenedReq) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// UserClosedReq is the request message for UserClosed RPC.
type UserClosedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClosedReq) Reset() {
	*x = UserClosedReq{}
	mi := &file_broker_protos_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClosedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClosedReq) ProtoMessage() {}

func (x *UserClosedReq) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClosedReq.ProtoReflect.Descriptor instead.
func (*UserClosedReq) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{9}
}

func (x *UserClosedReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserClosedReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// RaftMessage represents a Raft message
type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft message data in binary format
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_broker_protos_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_broker_protos_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_broker_protos_peer_proto_rawDescGZIP(), []int{10}
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_broker_protos_peer_proto protoreflect.FileDescriptor

const file_broker_protos_peer_proto_rawDesc = "" +
	"\n" +
	"\x18broker/protos/peer.proto\x12\x06protos\"\a\n" +
	"\x05Empty\",\n" +
	"\x06Target\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x10\n" +
	"\x03net\x18\x02 \x01(\tR\x03net\"7\n" +
	"\vIsOnlineReq\x12(\n" +
	"\atargets\x18\x01 \x03(\v2\x0e.protos.TargetR\atargets\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"P\n" +
	"\n" +
	"MessageReq\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12(\n" +
	"\atargets\x18\x04 \x03(\v2\x0e.protos.TargetR\atargets\"=\n" +
	"\vMessageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\"7\n" +
	"\vKickConnReq\x12(\n" +
	"\atargets\x18\x01 \x03(\v2\x0e.protos.TargetR\atargets\"\xa4\x01\n" +
	"\bInspects\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x05R\tuserCount\x12!\n" +
	"\fclient_count\x18\x03 \x01(\x05R\vclientCount\x12!\n" +
	"\fcluster_size\x18\x04 \x01(\x05R\vclusterSize\x12#\n" +
	"\rchannel_count\x18\x05 \x01(\x05R\fchannelCount\"^\n" +
	"\rUserOpenedReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x10\n" +
	"\x03net\x18\x03 \x01(\tR\x03net\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\"3\n" +
	"\rUserClosedReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\"!\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xbf\x03\n" +
	"\vPeerService\x12,\n" +
	"\aInspect\x12\r.protos.Empty\x1a\x10.protos.Inspects\"\x00\x127\n" +
	"\bIsOnline\x12\x13.protos.IsOnlineReq\x1a\x14.protos.IsOnlineResp\"\x00\x120\n" +
	"\bKickConn\x12\x13.protos.KickConnReq\x1a\r.protos.Empty\"\x00\x126\n" +
	"\tSendToAll\x12\x12.protos.MessageReq\x1a\x13.protos.MessageResp\"\x00\x12:\n" +
	"\rSendToTargets\x12\x12.protos.MessageReq\x1a\x13.protos.MessageResp\"\x00\x124\n" +
	"\n" +
	"UserOpened\x12\x15.protos.UserOpenedReq\x1a\r.protos.Empty\"\x00\x124\n" +
	"\n" +
	"UserClosed\x12\x15.protos.UserClosedReq\x1a\r.protos.Empty\"\x00\x127\n" +
	"\x0fSendRaftMessage\x12\x13.protos.RaftMessage\x1a\r.protos.Empty\"\x00B\n" +
	"Z\b./protosb\x06proto3"

var (
	file_broker_protos_peer_proto_rawDescOnce sync.Once
	file_broker_protos_peer_proto_rawDescData []byte
)

func file_broker_protos_peer_proto_rawDescGZIP() []byte {
	file_broker_protos_peer_proto_rawDescOnce.Do(func() {
		file_broker_protos_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)))
	})
	return file_broker_protos_peer_proto_rawDescData
}

var file_broker_protos_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_broker_protos_peer_proto_goTypes = []any{
	(*Empty)(nil),         // 0: protos.Empty
	(*Target)(nil),        // 1: protos.Target
	(*IsOnlineReq)(nil),   // 2: protos.IsOnlineReq
	(*IsOnlineResp)(nil),  // 3: protos.IsOnlineResp
	(*MessageReq)(nil),    // 4: protos.MessageReq
	(*MessageResp)(nil),   // 5: protos.MessageResp
	(*KickConnReq)(nil),   // 6: protos.KickConnReq
	(*Inspects)(nil),      // 7: protos.Inspects
	(*UserOpenedReq)(nil), // 8: protos.UserOpenedReq
	(*UserClosedReq)(nil), // 9: protos.UserClosedReq
	(*RaftMessage)(nil),   // 10: protos.RaftMessage
}
var file_broker_protos_peer_proto_depIdxs = []int32{
	1,  // 0: protos.IsOnlineReq.targets:type_name -> protos.Target
	1,  // 1: protos.MessageReq.targets:type_name -> protos.Target
	1,  // 2: protos.KickConnReq.targets:type_name -> protos.Target
	0,  // 3: protos.PeerService.Inspect:input_type -> protos.Empty
	2,  // 4: protos.PeerService.IsOnline:input_type -> protos.IsOnlineReq
	6,  // 5: protos.PeerService.KickConn:input_type -> protos.KickConnReq
	4,  // 6: protos.PeerService.SendToAll:input_type -> protos.MessageReq
	4,  // 7: protos.PeerService.SendToTargets:input_type -> protos.MessageReq
	8,  // 8: protos.PeerService.UserOpened:input_type -> protos.UserOpenedReq
	9,  // 9: protos.PeerService.UserClosed:input_type -> protos.UserClosedReq
	10, // 10: protos.PeerService.SendRaftMessage:input_type -> protos.RaftMessage
	7,  // 11: protos.PeerService.Inspect:output_type -> protos.Inspects
	3,  // 12: protos.PeerService.IsOnline:output_type -> protos.IsOnlineResp
	0,  // 13: protos.PeerService.KickConn:output_type -> protos.Empty
	5,  // 14: protos.PeerService.SendToAll:output_type -> protos.MessageResp
	5,  // 15: protos.PeerService.SendToTargets:output_type -> protos.MessageResp
	0,  // 16: protos.PeerService.UserOpened:output_type -> protos.Empty
	0,  // 17: protos.PeerService.UserClosed:output_type -> protos.Empty
	0,  // 18: protos.PeerService.SendRaftMessage:output_type -> protos.Empty
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_broker_protos_peer_proto_init() }
func file_broker_protos_peer_proto_init() {
	if File_broker_protos_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_protos_peer_proto_rawDesc), len(file_broker_protos_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broker_protos_peer_proto_goTypes,
		DependencyIndexes: file_broker_protos_peer_proto_depIdxs,
		MessageInfos:      file_broker_protos_peer_proto_msgTypes,
	}.Build()
	File_broker_protos_peer_proto = out.File
	file_broker_protos_peer_proto_goTypes = nil
	file_broker_protos_peer_proto_depIdxs = nil
}
