// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/pb/cable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmptyResp is a response message that does not contain any data.
type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_api_pb_cable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{0}
}

// ToAllReq is a request message to send a message to all users.
type ToAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qos           int32                  `protobuf:"varint,1,opt,name=qos,proto3" json:"qos,omitempty"`
	Kind          int32                  `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToAllReq) Reset() {
	*x = ToAllReq{}
	mi := &file_api_pb_cable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToAllReq) ProtoMessage() {}

func (x *ToAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToAllReq.ProtoReflect.Descriptor instead.
func (*ToAllReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{1}
}

func (x *ToAllReq) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *ToAllReq) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ToAllReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// ToUserReq is a request message to send a message to a specific user.
type ToUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Qos           int32                  `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`
	Kind          int32                  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       []byte                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToUserReq) Reset() {
	*x = ToUserReq{}
	mi := &file_api_pb_cable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUserReq) ProtoMessage() {}

func (x *ToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUserReq.ProtoReflect.Descriptor instead.
func (*ToUserReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{2}
}

func (x *ToUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ToUserReq) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *ToUserReq) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ToUserReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// ToChannelReq is a request message to send a message to a specific channel.
type ToChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Qos           int32                  `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`
	Kind          int32                  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       []byte                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToChannelReq) Reset() {
	*x = ToChannelReq{}
	mi := &file_api_pb_cable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToChannelReq) ProtoMessage() {}

func (x *ToChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToChannelReq.ProtoReflect.Descriptor instead.
func (*ToChannelReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{3}
}

func (x *ToChannelReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ToChannelReq) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *ToChannelReq) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ToChannelReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// MsgResp is a response message to indicate the result of a message sending operation.
type MsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResp) Reset() {
	*x = MsgResp{}
	mi := &file_api_pb_cable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResp) ProtoMessage() {}

func (x *MsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResp.ProtoReflect.Descriptor instead.
func (*MsgResp) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{4}
}

func (x *MsgResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MsgResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// JoinReq is a request message to join a specific channel.
type JoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Channels      map[string]string      `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	mi := &file_api_pb_cable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{5}
}

func (x *JoinReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *JoinReq) GetChannels() map[string]string {
	if x != nil {
		return x.Channels
	}
	return nil
}

// UserReq is a request message to identify a specific user.
type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_api_pb_cable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{6}
}

func (x *UserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// KickNodeReq is a request message to kick a specific node from the cluster.
type KickNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerID      uint64                 `protobuf:"varint,1,opt,name=brokerID,proto3" json:"brokerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNodeReq) Reset() {
	*x = KickNodeReq{}
	mi := &file_api_pb_cable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNodeReq) ProtoMessage() {}

func (x *KickNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNodeReq.ProtoReflect.Descriptor instead.
func (*KickNodeReq) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{7}
}

func (x *KickNodeReq) GetBrokerID() uint64 {
	if x != nil {
		return x.BrokerID
	}
	return 0
}

// OnlineResp is a response message to indicate whether a user is online.
type OnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineResp) Reset() {
	*x = OnlineResp{}
	mi := &file_api_pb_cable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResp) ProtoMessage() {}

func (x *OnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResp.ProtoReflect.Descriptor instead.
func (*OnlineResp) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{8}
}

func (x *OnlineResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ChannelsResp is a response message to list all channels a user is joined.
type ChannelsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      map[string]string      `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelsResp) Reset() {
	*x = ChannelsResp{}
	mi := &file_api_pb_cable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelsResp) ProtoMessage() {}

func (x *ChannelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_cable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelsResp.ProtoReflect.Descriptor instead.
func (*ChannelsResp) Descriptor() ([]byte, []int) {
	return file_api_pb_cable_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelsResp) GetChannels() map[string]string {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_api_pb_cable_proto protoreflect.FileDescriptor

const file_api_pb_cable_proto_rawDesc = "" +
	"\n" +
	"\x12api/pb/cable.proto\x12\x02pb\"\v\n" +
	"\tEmptyResp\"J\n" +
	"\bToAllReq\x12\x10\n" +
	"\x03qos\x18\x01 \x01(\x05R\x03qos\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\x05R\x04kind\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"]\n" +
	"\tToUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03qos\x18\x02 \x01(\x05R\x03qos\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\x05R\x04kind\x12\x18\n" +
	"\amessage\x18\x04 \x01(\fR\amessage\"h\n" +
	"\fToChannelReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x10\n" +
	"\x03qos\x18\x02 \x01(\x05R\x03qos\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\x05R\x04kind\x12\x18\n" +
	"\amessage\x18\x04 \x01(\fR\amessage\"9\n" +
	"\aMsgResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\"\x8f\x01\n" +
	"\aJoinReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x125\n" +
	"\bchannels\x18\x02 \x03(\v2\x19.pb.JoinReq.ChannelsEntryR\bchannels\x1a;\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\aUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\")\n" +
	"\vKickNodeReq\x12\x1a\n" +
	"\bbrokerID\x18\x01 \x01(\x04R\bbrokerID\"\x1c\n" +
	"\n" +
	"OnlineResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x87\x01\n" +
	"\fChannelsResp\x12:\n" +
	"\bchannels\x18\x01 \x03(\v2\x1e.pb.ChannelsResp.ChannelsEntryR\bchannels\x1a;\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa5\x03\n" +
	"\fCableService\x12)\n" +
	"\bIsOnline\x12\v.pb.UserReq\x1a\x0e.pb.OnlineResp\"\x00\x12(\n" +
	"\bKickUser\x12\v.pb.UserReq\x1a\r.pb.EmptyResp\"\x00\x12,\n" +
	"\bKickNode\x12\x0f.pb.KickNodeReq\x1a\r.pb.EmptyResp\"\x00\x12(\n" +
	"\tSendToAll\x12\f.pb.ToAllReq\x1a\v.pb.MsgResp\"\x00\x12*\n" +
	"\n" +
	"SendToUser\x12\r.pb.ToUserReq\x1a\v.pb.MsgResp\"\x00\x120\n" +
	"\rSendToChannel\x12\x10.pb.ToChannelReq\x1a\v.pb.MsgResp\"\x00\x12+\n" +
	"\vJoinChannel\x12\v.pb.JoinReq\x1a\r.pb.EmptyResp\"\x00\x12,\n" +
	"\fLeaveChannel\x12\v.pb.JoinReq\x1a\r.pb.EmptyResp\"\x00\x12/\n" +
	"\fListChannels\x12\v.pb.UserReq\x1a\x10.pb.ChannelsResp\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_api_pb_cable_proto_rawDescOnce sync.Once
	file_api_pb_cable_proto_rawDescData []byte
)

func file_api_pb_cable_proto_rawDescGZIP() []byte {
	file_api_pb_cable_proto_rawDescOnce.Do(func() {
		file_api_pb_cable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_cable_proto_rawDesc), len(file_api_pb_cable_proto_rawDesc)))
	})
	return file_api_pb_cable_proto_rawDescData
}

var file_api_pb_cable_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_pb_cable_proto_goTypes = []any{
	(*EmptyResp)(nil),    // 0: pb.EmptyResp
	(*ToAllReq)(nil),     // 1: pb.ToAllReq
	(*ToUserReq)(nil),    // 2: pb.ToUserReq
	(*ToChannelReq)(nil), // 3: pb.ToChannelReq
	(*MsgResp)(nil),      // 4: pb.MsgResp
	(*JoinReq)(nil),      // 5: pb.JoinReq
	(*UserReq)(nil),      // 6: pb.UserReq
	(*KickNodeReq)(nil),  // 7: pb.KickNodeReq
	(*OnlineResp)(nil),   // 8: pb.OnlineResp
	(*ChannelsResp)(nil), // 9: pb.ChannelsResp
	nil,                  // 10: pb.JoinReq.ChannelsEntry
	nil,                  // 11: pb.ChannelsResp.ChannelsEntry
}
var file_api_pb_cable_proto_depIdxs = []int32{
	10, // 0: pb.JoinReq.channels:type_name -> pb.JoinReq.ChannelsEntry
	11, // 1: pb.ChannelsResp.channels:type_name -> pb.ChannelsResp.ChannelsEntry
	6,  // 2: pb.CableService.IsOnline:input_type -> pb.UserReq
	6,  // 3: pb.CableService.KickUser:input_type -> pb.UserReq
	7,  // 4: pb.CableService.KickNode:input_type -> pb.KickNodeReq
	1,  // 5: pb.CableService.SendToAll:input_type -> pb.ToAllReq
	2,  // 6: pb.CableService.SendToUser:input_type -> pb.ToUserReq
	3,  // 7: pb.CableService.SendToChannel:input_type -> pb.ToChannelReq
	5,  // 8: pb.CableService.JoinChannel:input_type -> pb.JoinReq
	5,  // 9: pb.CableService.LeaveChannel:input_type -> pb.JoinReq
	6,  // 10: pb.CableService.ListChannels:input_type -> pb.UserReq
	8,  // 11: pb.CableService.IsOnline:output_type -> pb.OnlineResp
	0,  // 12: pb.CableService.KickUser:output_type -> pb.EmptyResp
	0,  // 13: pb.CableService.KickNode:output_type -> pb.EmptyResp
	4,  // 14: pb.CableService.SendToAll:output_type -> pb.MsgResp
	4,  // 15: pb.CableService.SendToUser:output_type -> pb.MsgResp
	4,  // 16: pb.CableService.SendToChannel:output_type -> pb.MsgResp
	0,  // 17: pb.CableService.JoinChannel:output_type -> pb.EmptyResp
	0,  // 18: pb.CableService.LeaveChannel:output_type -> pb.EmptyResp
	9,  // 19: pb.CableService.ListChannels:output_type -> pb.ChannelsResp
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_pb_cable_proto_init() }
func file_api_pb_cable_proto_init() {
	if File_api_pb_cable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_cable_proto_rawDesc), len(file_api_pb_cable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_cable_proto_goTypes,
		DependencyIndexes: file_api_pb_cable_proto_depIdxs,
		MessageInfos:      file_api_pb_cable_proto_msgTypes,
	}.Build()
	File_api_pb_cable_proto = out.File
	file_api_pb_cable_proto_goTypes = nil
	file_api_pb_cable_proto_depIdxs = nil
}
