// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/pb/cable.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CableService_IsOnline_FullMethodName      = "/pb.CableService/IsOnline"
	CableService_KickUser_FullMethodName      = "/pb.CableService/KickUser"
	CableService_SendToAll_FullMethodName     = "/pb.CableService/SendToAll"
	CableService_SendToUser_FullMethodName    = "/pb.CableService/SendToUser"
	CableService_SendToChannel_FullMethodName = "/pb.CableService/SendToChannel"
	CableService_JoinChannel_FullMethodName   = "/pb.CableService/JoinChannel"
	CableService_LeaveChannel_FullMethodName  = "/pb.CableService/LeaveChannel"
	CableService_GetChannels_FullMethodName   = "/pb.CableService/GetChannels"
)

// CableServiceClient is the client API for CableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CableServiceClient interface {
	IsOnline(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*OnlineResp, error)
	KickUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*EmptyResp, error)
	SendToAll(ctx context.Context, in *ToAllReq, opts ...grpc.CallOption) (*MsgResp, error)
	SendToUser(ctx context.Context, in *ToUserReq, opts ...grpc.CallOption) (*MsgResp, error)
	SendToChannel(ctx context.Context, in *ToChannelReq, opts ...grpc.CallOption) (*MsgResp, error)
	JoinChannel(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*EmptyResp, error)
	LeaveChannel(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetChannels(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*ChannelsResp, error)
}

type cableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCableServiceClient(cc grpc.ClientConnInterface) CableServiceClient {
	return &cableServiceClient{cc}
}

func (c *cableServiceClient) IsOnline(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*OnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineResp)
	err := c.cc.Invoke(ctx, CableService_IsOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) KickUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, CableService_KickUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) SendToAll(ctx context.Context, in *ToAllReq, opts ...grpc.CallOption) (*MsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgResp)
	err := c.cc.Invoke(ctx, CableService_SendToAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) SendToUser(ctx context.Context, in *ToUserReq, opts ...grpc.CallOption) (*MsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgResp)
	err := c.cc.Invoke(ctx, CableService_SendToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) SendToChannel(ctx context.Context, in *ToChannelReq, opts ...grpc.CallOption) (*MsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgResp)
	err := c.cc.Invoke(ctx, CableService_SendToChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) JoinChannel(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, CableService_JoinChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) LeaveChannel(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, CableService_LeaveChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) GetChannels(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*ChannelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelsResp)
	err := c.cc.Invoke(ctx, CableService_GetChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CableServiceServer is the server API for CableService service.
// All implementations must embed UnimplementedCableServiceServer
// for forward compatibility.
type CableServiceServer interface {
	IsOnline(context.Context, *UserReq) (*OnlineResp, error)
	KickUser(context.Context, *UserReq) (*EmptyResp, error)
	SendToAll(context.Context, *ToAllReq) (*MsgResp, error)
	SendToUser(context.Context, *ToUserReq) (*MsgResp, error)
	SendToChannel(context.Context, *ToChannelReq) (*MsgResp, error)
	JoinChannel(context.Context, *JoinReq) (*EmptyResp, error)
	LeaveChannel(context.Context, *JoinReq) (*EmptyResp, error)
	GetChannels(context.Context, *UserReq) (*ChannelsResp, error)
	mustEmbedUnimplementedCableServiceServer()
}

// UnimplementedCableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCableServiceServer struct{}

func (UnimplementedCableServiceServer) IsOnline(context.Context, *UserReq) (*OnlineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsOnline not implemented")
}
func (UnimplementedCableServiceServer) KickUser(context.Context, *UserReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedCableServiceServer) SendToAll(context.Context, *ToAllReq) (*MsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToAll not implemented")
}
func (UnimplementedCableServiceServer) SendToUser(context.Context, *ToUserReq) (*MsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToUser not implemented")
}
func (UnimplementedCableServiceServer) SendToChannel(context.Context, *ToChannelReq) (*MsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToChannel not implemented")
}
func (UnimplementedCableServiceServer) JoinChannel(context.Context, *JoinReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinChannel not implemented")
}
func (UnimplementedCableServiceServer) LeaveChannel(context.Context, *JoinReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveChannel not implemented")
}
func (UnimplementedCableServiceServer) GetChannels(context.Context, *UserReq) (*ChannelsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannels not implemented")
}
func (UnimplementedCableServiceServer) mustEmbedUnimplementedCableServiceServer() {}
func (UnimplementedCableServiceServer) testEmbeddedByValue()                      {}

// UnsafeCableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CableServiceServer will
// result in compilation errors.
type UnsafeCableServiceServer interface {
	mustEmbedUnimplementedCableServiceServer()
}

func RegisterCableServiceServer(s grpc.ServiceRegistrar, srv CableServiceServer) {
	// If the following call panics, it indicates UnimplementedCableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CableService_ServiceDesc, srv)
}

func _CableService_IsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).IsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_IsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).IsOnline(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_KickUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).KickUser(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_SendToAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).SendToAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_SendToAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).SendToAll(ctx, req.(*ToAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_SendToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).SendToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_SendToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).SendToUser(ctx, req.(*ToUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_SendToChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).SendToChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_SendToChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).SendToChannel(ctx, req.(*ToChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_JoinChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).JoinChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_JoinChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).JoinChannel(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_LeaveChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).LeaveChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_LeaveChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).LeaveChannel(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_GetChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).GetChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_GetChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).GetChannels(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CableService_ServiceDesc is the grpc.ServiceDesc for CableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CableService",
	HandlerType: (*CableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsOnline",
			Handler:    _CableService_IsOnline_Handler,
		},
		{
			MethodName: "KickUser",
			Handler:    _CableService_KickUser_Handler,
		},
		{
			MethodName: "SendToAll",
			Handler:    _CableService_SendToAll_Handler,
		},
		{
			MethodName: "SendToUser",
			Handler:    _CableService_SendToUser_Handler,
		},
		{
			MethodName: "SendToChannel",
			Handler:    _CableService_SendToChannel_Handler,
		},
		{
			MethodName: "JoinChannel",
			Handler:    _CableService_JoinChannel_Handler,
		},
		{
			MethodName: "LeaveChannel",
			Handler:    _CableService_LeaveChannel_Handler,
		},
		{
			MethodName: "GetChannels",
			Handler:    _CableService_GetChannels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/cable.proto",
}
