// Code generated by Kitex v0.15.2. DO NOT EDIT.

package service

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "sutext.github.io/cable/api/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"join": kitex.NewMethodInfo(
		joinHandler,
		newServiceJoinArgs,
		newServiceJoinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"leave": kitex.NewMethodInfo(
		leaveHandler,
		newServiceLeaveArgs,
		newServiceLeaveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"publish": kitex.NewMethodInfo(
		publishHandler,
		newServicePublishArgs,
		newServicePublishResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	serviceServiceInfo                = NewServiceInfo()
	serviceServiceInfoForClient       = NewServiceInfoForClient()
	serviceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return serviceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return serviceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return serviceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Service"
	handlerType := (*api.Service)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func joinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ServiceJoinArgs)
	realResult := result.(*api.ServiceJoinResult)
	success, err := handler.(api.Service).Join(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServiceJoinArgs() interface{} {
	return api.NewServiceJoinArgs()
}

func newServiceJoinResult() interface{} {
	return api.NewServiceJoinResult()
}

func leaveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ServiceLeaveArgs)
	realResult := result.(*api.ServiceLeaveResult)
	success, err := handler.(api.Service).Leave(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServiceLeaveArgs() interface{} {
	return api.NewServiceLeaveArgs()
}

func newServiceLeaveResult() interface{} {
	return api.NewServiceLeaveResult()
}

func publishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ServicePublishArgs)

	err := handler.(api.Service).Publish(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newServicePublishArgs() interface{} {
	return api.NewServicePublishArgs()
}

func newServicePublishResult() interface{} {
	return api.NewServicePublishResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Join(ctx context.Context, req *api.JoinRequest) (r *api.JoinResponse, err error) {
	var _args api.ServiceJoinArgs
	_args.Req = req
	var _result api.ServiceJoinResult
	if err = p.c.Call(ctx, "join", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Leave(ctx context.Context, req *api.JoinRequest) (r *api.JoinResponse, err error) {
	var _args api.ServiceLeaveArgs
	_args.Req = req
	var _result api.ServiceLeaveResult
	if err = p.c.Call(ctx, "leave", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Publish(ctx context.Context, req *api.PublishRequest) (err error) {
	var _args api.ServicePublishArgs
	_args.Req = req
	var _result api.ServicePublishResult
	if err = p.c.Call(ctx, "publish", &_args, &_result); err != nil {
		return
	}
	return nil
}
