// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/listener/pb/bytes.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BytesService_Connect_FullMethodName = "/pb.BytesService/Connect"
)

// BytesServiceClient is the client API for BytesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BytesServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Bytes, Bytes], error)
}

type bytesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBytesServiceClient(cc grpc.ClientConnInterface) BytesServiceClient {
	return &bytesServiceClient{cc}
}

func (c *bytesServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Bytes, Bytes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BytesService_ServiceDesc.Streams[0], BytesService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Bytes, Bytes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BytesService_ConnectClient = grpc.BidiStreamingClient[Bytes, Bytes]

// BytesServiceServer is the server API for BytesService service.
// All implementations must embed UnimplementedBytesServiceServer
// for forward compatibility.
type BytesServiceServer interface {
	Connect(grpc.BidiStreamingServer[Bytes, Bytes]) error
	mustEmbedUnimplementedBytesServiceServer()
}

// UnimplementedBytesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBytesServiceServer struct{}

func (UnimplementedBytesServiceServer) Connect(grpc.BidiStreamingServer[Bytes, Bytes]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedBytesServiceServer) mustEmbedUnimplementedBytesServiceServer() {}
func (UnimplementedBytesServiceServer) testEmbeddedByValue()                      {}

// UnsafeBytesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BytesServiceServer will
// result in compilation errors.
type UnsafeBytesServiceServer interface {
	mustEmbedUnimplementedBytesServiceServer()
}

func RegisterBytesServiceServer(s grpc.ServiceRegistrar, srv BytesServiceServer) {
	// If the following call pancis, it indicates UnimplementedBytesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BytesService_ServiceDesc, srv)
}

func _BytesService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BytesServiceServer).Connect(&grpc.GenericServerStream[Bytes, Bytes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BytesService_ConnectServer = grpc.BidiStreamingServer[Bytes, Bytes]

// BytesService_ServiceDesc is the grpc.ServiceDesc for BytesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BytesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BytesService",
	HandlerType: (*BytesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BytesService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/listener/pb/bytes.proto",
}
