# Tempo Helm values (单体模式)
tempo:
  config:
    storage:
      trace:
        backend: s3
        s3:
          bucket: test-tempo-1314353702
          endpoint: cos.ap-chengdu.myqcloud.com
          access_key: AKIDGj04vb3JL9oIYX4CAvWv9Aya0CZlncDb
          secret_key: PccP2UjlZCeXCfMwKYbR5Yw7xcGoHahb

    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

service:
  type: ClusterIP
  ports:
    http: 3200
    grpc: 4317

ingress:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m